### PR TITLE
Update ITEM_Thai.tsv 1-30

### PR DESCRIPTION
**Pull request by shadecaius**
Translate only description.
Item name use English because Thai player familiar with English item name more than Thai item name.

### CODE REVIEW

**Comment by imcgames** [comment]
Please leave a comment like "Good to merge" for us to understand it's correct PR or not. Thank you.

**Comment by thetidman** [comment]
Good to merge

**Comment by shadecaius** [comment]
its all right. Good to merge. :smile:

**Comment by imcgames** [comment]
Thank you @shadecaius :+1:

**Comment by shadecaius** [comment]
@po456asd Comment like this at your Pull Request. :sweat_smile:

**Pull request merged**
