### PR TITLE
Update QUEST_JOBSTEP_Thai.tsv

### PR DESCRIPTION
**Pull request by puffychan**
My first Translation for learn how to add translations and how the system work.
- ถ้าแปลใช้สำนวนเรียกสรรพนาม ข้า เจ้า ท่าน จะดีไหม?

### CODE REVIEW

**Comment by tinnan** [comment]
I agreed with you about using historical styled pronouns.

For your pull request, I think you could just translate "doll" to "ตุ๊กตา" because Bokor is a class which uses Voodoo skills. (See [Bokor class](http://www.tosbase.com/game/classes/Bokor)) And if you search for Bokor gameplay footage you will see they use voodoo doll to inflict damage to enemies.

Some typos on line 13: "...ข้าจะดูว่า**เข้า**สามารถช่วยงานวิจัยของข้าได้ดี**หขนาด**ไหน..."
On line 16: Please move the `{nl}` tag to the end of the first sentence. (behind the word "แล้ว")

Lastly, Please read README.md file and Guidelines on how to send a proper pull request.
You can see other merged pull requests for example.

**Comment by tinnan** [comment]
Glad to help :D

But please be careful with the character between the codes (e.g. QUEST_JOBSTEP_20150317_XXXXXX) and the translation texts.
The character must be a "TAB" not a "Space".

Check line 10, 11, 13, 14, 15.
Fix them and this PR should be good to merge.

**Comment by puffychan** [comment]
-Remove another $
-fix TAB line 10, 11, 13, 14, 15.
@tinnan Thank you for your help. I have learned many things about how to send PR.

Now, do I have to say something like "Good to merge" and close my PR ?

Note: I've decided to using historical styled pronouns just for more fantasy dialogue.

**Comment by tinnan** [comment]
@puffychan yes, you have to say it and wait for IMC to merge the PR. (Do not close it)

p.s. You say "Good to merge" when you're confident the PR is correct. But if you are not sure and want someone to review your works, just say so. Then you can say it is good to merge later.

**Comment by puffychan** [comment]
It's Final Editing.
Now "Good to merge"
Thank you ^0^

**Comment by imcgames** [comment]
Thank you @puffychan @tinnan :+1:

**Pull request merged**
